name: Publish wordslab-webscraper release

on:
  push:
    tags:
      - "v*"

env:
  DOTNET_VERSION: '7.0.202' # The .NET SDK version to use

jobs:
  publish:
    name: Build and publish new wordslab-webscraper release
    runs-on: ubuntu-latest

    steps:
    - name: Check out wordslab-webscraping repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install wordslab.webscraper dependencies
      run: |
        cd wordslab.webscraper
        dotnet restore
      
    - name: Build wordslab.webscraper
      run: |
        cd wordslab.webscraper
        dotnet build --no-restore -c Release
              
    - name: Publish wordslab-webscraper extractor for all operating systems
      run: |
        cd wordslab.webscraper
        dotnet publish -c Release -p:PublishProfile=windows
        dotnet publish -c Release -p:PublishProfile=linux
        dotnet publish -c Release -p:PublishProfile=macos-x64

    - name: Create a zip archive for Windows
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        directory: wordslab.webscraper/bin/Release/net7.0/publish/win-x64/
        filename: 'wordslab-webscraper-win-x64.zip'

    - name: Create a tar.gz archive for Linux
      run: |
        cd wordslab.webscraper/bin/Release/net7.0/publish/linux-x64/
        tar -zcvf wordslab-webscraper-linux-x64.tar.gz *

    - name: Create a tar.gz archive for macOS
      run: |
        cd wordslab.webscraper/bin/Release/net7.0/publish/osx-x64/
        tar -zcvf wordslab-webscraper-osx-x64.tar.gz *

    - name: Create new release
      uses: marvinpinto/action-automatic-releases@v1.2.1      
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        files: |
          wordslab.webscraper/bin/Release/net7.0/publish/win-x64/wordslab-webscraper-win-x64.zip
          wordslab.webscraper/bin/Release/net7.0/publish/linux-x64/wordslab-webscraper-linux-x64.tar.gz
          wordslab.webscraper/bin/Release/net7.0/publish/osx-x64/wordslab-webscraper-osx-x64.tar.gz